config/routes.rb
Rails.application.routes.draw do

  get 'blogs/index'

  get 'blogs/new'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :blogs

  root 'welcome#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user

  def self.search(search)
    where("user_id LIKE?","%#{search}")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :blogs
  enum role: [:user, :vip, :admin]
 after_initialize :set_default_role, :if => :new_record?

 def set_default_role
   self.role ||= :user
 end

 # Include default devise modules. Others available are:
 # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    include Pundit
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception

  private

      def user_not_authorized
      	flash[:alert]= "Access Denied."
      	redirect_to(request.referrer) || root_path
      end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :authenticate_user!
  def index
    if params[:blog] and params[:blog][:user_id]
      @blogs = Blog.search(params[:blog][:user_id])
    else
      @blogs = Blog.all
    end
    
 end

  def new
    @blog = Blog.new

  end
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to :action => 'index'
    else
      render(:action => 'new')
    end
  end
  def blog_params
    params.require(:blog).permit(:bodyText, :Money, :fee)
  end
end

app/controllers/myviews_controller.rb
class MyviewsController < ApplicationController
  def index
    @myblog = Blog.search(current_user.id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:firstname, :surname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :surname, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
   @Users = User.all
  end

  def show
    @Users = User.find(params[:id])
  end

  def update
    @Users = User.find(params[:id])
    if @Users.update_attributes(secure_params)
       redirect_to users_path, :notice =>"Everything is okay"
    else
       redirect_to users_path, :alert =>"Didn't happen"
    end
  end
  private
  def secure_params
    params.require(:user).permit(:role)

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/index.html.erb
<h1>Articles</h1>
<p>List of all the current articles</p>
 <%= form_tag blogs_path, :method => 'get' do %>
   <%= collection_select :blog, :user_id, User.all, :id, :firstname, prompt: true %>
   <%= submit_tag "Submit" %>
  <% end %>
<% @blogs.each do |harry| %>
<li><%= harry.bodyText %></li>
<%= harry.fee %></li>
<% end %>

app/views/blogs/new.html.erb
<h1>New Article</h1>

<%= "This article is written by #{current_user.firstname} "%>

<div class='span6'>
<%= form_for @blog do |h| %>
  <br />
  <%= h.text_area :bodyText, cols: 50, rows: 4, class: "message" %>
  <br />
  <%= h.text_field :fee %>
  <%= h.hidden_field :user_id, value: current_user.id%>

  <%= h.submit 'add' %>
<% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= render 'layouts/navigation_links_left' %>
    </div>
    <div class="collapse navbar-collapse navbar-right">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links_left.html.erb
<%= link_to 'Home', root_path, class: 'navbar-brand' %>

<%= link_to 'Articles', blogs_path, class: 'navbar-brand' %>
<%= link_to 'New Article', blogs_new_path, class: 'navbar-brand' %>


<%= link_to 'About', 'about', class: 'navbar-brand' %>
<% if user_signed_in? %>
  <%= link_to 'Edit account', edit_user_registration_path, class: 'navbar-brand'%>
  <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' , class: 'navbar-brand'%>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/layouts/_navigation_links_right.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
	<li class = "dropdown">
		<a href = "#" data-toggle = "dropdown" class = "dropdown-toggle">Profile<b class = "caret"></b></a>

		<ul class = "dropdown-menu">
			<li><%= link_to 'View account', edit_user_registration_path %></li>

			<% if current_user.admin? %>
				<li><%= link_to 'Manage accounts', users_path %>
			<% end %>

			<li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
		</ul>
	</li>
<% else %>
	<li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pundit" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Pundit" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/myviews/index.html.erb
<h1>Myviews#index</h1>
<p>Find me in app/views/myviews/index.html.erb</p>
<%= params.inspect %>

<% @myblog.each do |h| %>
  <li><%= h.bodyText %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% @Users.each do |user| %>
<%= link_to user.email, user %>
	<%= form_for(user) do |f| %>

	<%= f.select(:role, User.roles.keys.map{|role|[role.titleize,role]})%>
	<%= f.submit 'change role', :class => 'button-xs' %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/index.html.erb
<h1>Home page</h1>